black = "#000000"
red = "#CD3131"
green = "#0DBC79"
yellow = "#E5E510"
blue = "#2472C8"
magenta = "#BC3FBC"
cyan = "#11A8CD"
white = "#E5E5E5"
bright_black = "#666666"
bright_red = "#F14C4C"
bright_green = "#23D18B"
bright_yellow = "#F5F543"
bright_blue = "#3B8EEA"
bright_magenta = "#D670D6"
bright_cyan = "#29B8DB"
bright_white = "#E5E5E5"
